services:
  kafdrop:
    image: docker.io/obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    environment:
      JVM_OPTS: -Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
      KAFKA_BROKERCONNECT: 52.77.110.196:9092
      # Optional security values can be provided from the host environment.
      # KAFKA_PROPERTIES: ${KAFKA_PROPERTIES:-}
      # KAFKA_TRUSTSTORE: ${KAFKA_TRUSTSTORE:-}
