services:
    mysql:
        image: docker.io/library/mysql:8
        environment:
            # - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=localSQL
            # - MYSQL_DATABASE=db-name
        ports:
            - 3306:3306
    
    adminer:
      image: docker.io/library/adminer:4
      ports:
        - 8080:8080
