version: "3"

services:
  nexus3:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./data/nexus-data:/nexus-data
