services:
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - phpmyadmin_session:/sessions
    environment:
     - PMA_ARBITRARY=1
    # restart: always
volumes:
  phpmyadmin_session:
