services:
  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui
    ports:
      - "8001:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/sample.yml
