version: "3"
services:
  wiremock:
    ports:
      - "8088:8080"
    volumes:
      - "./data/wiremock:/home/wiremock"
    image: rodolpheche/wiremock:2.27.1
    command: --disable-banner true --container-threads 100 --proxy-all="http://localhost:8088" --record-mappings
